.gitignore
Vagrantfile
bootstrap.sh

Automating the installation of Pipenv on the Vagrant box (Closes #7).
IMPORTANT: this PR is based on PR #2
Once it is merged, this PR will need to be rebased before it can be merged.

Create a bootstrap script to install Pipenv

---

README.md

- using more of the Markup language capabilities 
- added teammates names  
- added contribution instructions
- added badges indicating PRs' status, issues' status, and top language used in the project
- Explained more thoroughly about the project, and the purpose of it
fix #5 
closes #11

Upgrade and fix readme

---

apphomepage/admin.py
apphomepage/apps.py
apphomepage/models.py
apphomepage/templates/apphomepage/homepage.html
apphomepage/tests.py
apphomepage/views.py
picATrip/settings.py
picATrip/urls.py

-generate app files under apphomepage dir
create homepage.html file under apphomepage/templates/apphomepage/
-set a function called homepage on views.py
in order to render the homepage.html file
-update urls.py in order to connect
between the http request to the views.homepage function
closes #6

Add homepage html

---

.github/workflows/flake8.yml
Pipfile
Pipfile.lock

- Set up GitHub actions to run flake8 on the code as we submit
new PRs.
- Create .github/workflows directory and the file flake8.yml
inside.
- Update Pipfile files.
#15

Install flake8

---

apphomepage/admin.py
apphomepage/models.py
apphomepage/tests.py
apphomepage/views.py

fix the following notes:
models.py:1:1: F401 'django.db.models' imported but unused
views.py:3:1: E302 expected 2 blank lines, found 1
views.py:5:1: W391 blank line at end of file
tests.py:1:1: F401 'django.test.TestCase' imported but unused
admin.py:1:1: F401 'django.contrib.admin' imported but unused
closes #24

fix flake8 notes

---

picATrip/settings.py
picATrip/urls.py
pickATrip_django_apps/templates/pickATrip_django_apps/about.html
pickATrip_django_apps/templates/pickATrip_django_apps/base.html
pickATrip_django_apps/templates/pickATrip_django_apps/homepage.html
pickATrip_django_apps/views.py
users/admin.py
users/apps.py
users/forms.py
users/models.py
users/templates/users/register.html
users/tests.py
users/views.py

- Creating a users app 
- Creating a registration page
- Creating a base template as the frame for all pages in the application.
- Adding the application a starter template of bootstrap
- After registering correctly you will redirect to the homepage and a confirmation for registration will pops up
After running 'vagrant up' the 'registration' page can be accessed at:
> http://127.0.0.1:8000/register/
**The registration page should look like the following:**
closes #41 #42

Creating a users app

---

Pipfile
Pipfile.lock
picATrip/settings.py
picATrip/urls.py
users/templates/users/login.html
users/templates/users/logout.html
users/templates/users/profile.html
users/templates/users/register.html
users/views.py

- Creating an authentication system for our application
- Users can login and logout
- Creating login.html, logout.html and profile.html
After running 'vagrant up':
The User can register at: http://127.0.0.1:8000/register/
The User can log-in at: http://127.0.0.1:8000/login/
The User can log-out at: http://127.0.0.1:8000/logout/
The User must be logged-in in order to access http://127.0.0.1:8000/profile/
If the User did not logged-in he will redirect to the login page.
closes #50

Creating Login and Logout System

---

README.md
pickATrip_django_apps/templates/pickATrip_django_apps/about.html
pickATrip_django_apps/templates/pickATrip_django_apps/homepage.html

- updating content in [homepage.html][1] files for supporting
- updated [about.html][2] content to consist of readme file content and updated
[readme.md][3] file due to the fact one of the teammates has left
minor changes in the main pages of the app
closes #65

Small content changes in html pages

---

.github/workflows/pytest.yml
Pipfile
Pipfile.lock
Post/models.py
Post/tests.py
pytest.ini

- Adding PyTest files and settings (pytest.ini)
- Adding a file to Github workflow in order to make it run when making a new PR (pytest.yml)
- Modify Pipfile and Pipfile.lock (by Django)
- adding a basic test for post model
closes #81
closes #83

Adding PyTest

---

pickATrip_django_apps/templates/pickATrip_django_apps/base.html

remove footer position fixed
set content and footer min hight
closes #70

Fix content overflow bug

---

Post/tests/test_url_posts.py
pickATrip_django_apps/tests/test_pickATrip_django_apps_urls.py
users/tests/test_users_urls.py

Add Url tests for Homepage,about

---

Post/tests/test_url_posts.py
pickATrip_django_apps/tests/test_pickATrip_django_apps_urls.py
users/tests/test_users_urls.py

PR #91 failed the 'black' tests since there were errors on files on the main branch.
This PR fixes the relevant files.

Fixing errors on the main branch

---

Post/tests/test_url_posts.py
commenting_system/models.py
commenting_system/tests.py
pickATrip_django_apps/tests/test_pickATrip_django_apps_urls.py
users/tests/test_users_urls.py

- Added tests for the comment model [commenting_system/models.py][1]
testing the model functions and the DB functionality
- Added model function to the [commenting_system/models.py][2] file to
support testing and simulate user/admin operations without using the
client layer
Adding tests to the comment model and supporting model function
closes #77

Adding comment model functions and tests for the commenting system

---

Post/migrations/0002_test_data.py
Post/templates/Post/postList.html

**Updated 'postList.html' to use the base template** - 'Post/templates/Post/postList.html' modified.
Now this page will be in the agreed format.
**Update HTML page to contain photos:**
* Update 'localhost:8000/postList' so a post in the list will contain a photo -  'Post/templates/Post/postList.html' modified.
* Update 'test data' so the URL will be a valid one - 'Post/migrations/0002_test_data.py' modified.
closes #94
closes #101

Update 'postList.html' to use the base template and to contain photos

---

Post/forms.py
Post/templates/Post/createPost.html
Post/tests.py
Post/tests/test_url_posts.py
Post/views.py
picATrip/urls.py
pickATrip_django_apps/templates/pickATrip_django_apps/base.html

A registered user can add a new post at: '127.0.0.1:8000/createPost/'.
- created a view function - Post/views.py modified.
- added a new URL for this feature -  picATrip/urls.py modified.
- created a form for this feature - Post/forms.py created.
- created a HTML page -  Post/templates/Post/createPost.html created.
These changes were made to create a user interface for the feature of creating a new post.
closes #96

Adding a 'Create a new post' feature

---

Post/models.py
Post/tests.py

- Test for creation
- Test for deletion
- Test for 'all_posts' function 
- Test for comments of a post
All the tests were added to 'Post/tests.py'.
A new function ('all_posts') added to 'Post' model and as a result, Post/models.py was modified.
**I added these tests so we can test the functionality of 'Post' model.**
* I will be happy to hear suggestions for tests you think I should add.
closes #90

Adding tests for 'Post' model

---

Post/templates/Post/postList.html
Post/templates/Post/post_detail.html
commenting_system/migrations/0002_test_data.py
pickATrip_django_apps/templates/pickATrip_django_apps/base.html

- Changed the order of the links in the navigation bar - pickATrip_django_apps/templates/pickATrip_django_apps/base.html modified.
- Changed the URLs to valid ones in comments test-data - commenting_system/migrations/0002_test_data.py modified
- The user will be able to click on an image in the list of posts and reach the relevant post details - Post/templates/Post/postList.html modified.
- Changed the view of a single post to contain an image - Post/templates/Post/post_detail.html modified.
Because I changed the 'test data' files, before you check the changes - do the following steps:
- run vagrant halt
- delete 'db.sqlite3'
- vagrant up
- vagrant provision

Changes related to site aesthetics

---

Post/templates/Post/postList.html

using the "album" example from bootstrap
https://getbootstrap.com/docs/5.0/examples/album/
closes #112

Add Style to PostList Page

---

Post/templates/Post/postList.html
Post/tests/test_url_posts.py
Post/tests/test_views_posts.py
Post/urls.py
Post/views.py
picATrip/settings.py
pickATrip_django_apps/templates/pickATrip_django_apps/base.html

add search text filed and button to the navbar
add postListSearch to Post/views and to the URLs
change base.html colors style
closes #125

Add Search option

---

Post/migrations/0002_test_data.py
Post/templates/Post/postList.html
Post/tests/test_views_posts.py
Post/views.py
README.md
commenting_system/migrations/0002_test_data.py
pickATrip_django_apps/templates/pickATrip_django_apps/about.html
pickATrip_django_apps/templates/pickATrip_django_apps/base.html
users/tests/test_profile.py
users/views.py

- Changing test data and adding 2 more posts
- Adding titles to the pages
- Limit the number of words in the description in postList
- Changing 'picATrip' to 'PicATrip' in readme and about
closes #134

Making content changes

---

Post/templates/Post/deletePost.html
Post/templates/Post/post_detail.html
Post/tests.py
Post/tests/test_url_posts.py
Post/tests/test_views_posts.py
Post/urls.py
Post/views.py

- created a class-based view for the feature - Post/views.py and Post/urls.py modified.
- created a template and for the HTML page - Post/templates/Post/deletePost.html created.
- Added an 'delete' button in 'post_detail.html' - Post/templates/Post/post_detail.html modified.
You can test this feature in the following way:
- Log in
- Create a new post
- Go to the list of posts
- Go to the details of the post you created (and you will see a 'delete' button).
- Delete your post and then check the post list.
closes #117

Adding 'delete a post' feature

---

Post/templates/Post/post_detail.html
Post/views.py

(based on PR #142 that accidentally closed)
- Adding better styling to comments, adding profile pictures, making the appearance more user-friendly,
- Adding label counters functionality (showing per post how much of each label has been chosen by all commenters)
- Styling photos and indentation to distinguish between comments and post details,
as well as distinguish between a situation where a specific post has no comments and a specific post with at least
one comment - change will appear on the title of the comments section.
closes #141

Styling post detail page and adding pictures

---

Post/tests.py
Post/tests/test_views_posts.py

Adding view tests and general tests for 'Create a post', 'Post detail' and 'View posts' features.
Post/tests/test_views_posts.py  and   Post/tests.py modified.
closes #119

Update test for 'Post' model features

---

Post/templates/Post/post_detail.html
README.md
pickATrip_django_apps/templates/pickATrip_django_apps/about.html

- Post/templates/Post/post_detail.html  modified.
- pickATrip_django_apps/templates/pickATrip_django_apps/about.html modified.
- README.md modified.
closes #152

Adding date field to 'post detail' page and update 'about' page

---

pickATrip_django_apps/templates/pickATrip_django_apps/base.html

Fixing 2 missing lines for PR #155

Fix 2 missing lines for the TIMEZONE fix PR
